repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-merge-conflict
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: no-commit-to-branch
        args: [-b, main]
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.15.0
    hooks:
      - id: check-github-workflows
      - id: check-jsonschema
        name: "Check Artifacts Valid JSON Schema"
        files: ^definitions/
        types: [json]
        args: ["--check-metaschema"]
