module.exports = {
  docs: [
    "introduction",
    {
      type: "category",
      label: "Getting Started",
      items: [{ type: "autogenerated", dirName: "getting_started" }],
    },
    {
      type: "category",
      label: "Concepts",
      items: [{ type: "autogenerated", dirName: "concepts" }],
    },
    {
      type: "category",
      label: "Applications",
      items: [{ type: "autogenerated", dirName: "applications" }],
    },
    {
      type: "category",
      label: "Provisioners",
      items: [{ type: "autogenerated", dirName: "provisioners" }],
    },
    {
      type: "category",
      label: "CI/CD",
      items: [{ type: "autogenerated", dirName: "ci_cd" }],
    },
    {
      type: "category",
      label: "Preview Environments",
      items: [{ type: "autogenerated", dirName: "preview_environments" }],
    },
    {
      type: "category",
      label: "CLI",
      link: { type: "doc", id: "cli/cli-overview" },
      items: [{ type: "autogenerated", dirName: "cli" }],
    },
    {
      type: "category",
      label: "Security",
      items: [{ type: "autogenerated", dirName: "security" }],
    },
    {
      type: "category",
      label: "Self-Hosted",
      items: [{ type: "autogenerated", dirName: "self_hosted" }],
    },
    {
      type: "category",
      label: "Guides",
      items: [{ type: "autogenerated", dirName: "guides" }],
    },
    {
      type: "category",
      label: "JSON Schema Cheat Sheet",
      items: [{ type: "autogenerated", dirName: "json_schema_cheat_sheet" }],
    },
    {
      type: "category",
      label: "GraphQL API",
      items: [
        {
          type: "doc",
          id: "swapi",
          label: "Overview"
        },
        {
          type: "category",
          label: "Queries",
          items: [{ type: "autogenerated", dirName: "swapi/operations/queries" }],
        },
        {
          type: "category",
          label: "Mutations",
          items: [{ type: "autogenerated", dirName: "swapi/operations/mutations" }],
        },
        {
          type: "category",
          label: "Types",
          items: [{ type: "autogenerated", dirName: "swapi/types" }],
        },
      ],
    },
    "troubleshooting",
  ]
};
